# =============================================
# CodeCollab - Application Configuration
# =============================================

# Server
server.port=8085

# =============================================
# DATABASE - Replace with your Render credentials
# =============================================
spring.datasource.url=jdbc:postgresql://dpg-d8j648rtqb8s73bqhpb0-a.oregon-postgres.render.com/codecollab_m1ot
spring.datasource.username=codecollab_m1ot_user
spring.datasource.password=jAxEsLcDXHppnolTasxv7bIifCWEgHxO
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =============================================
# JWT Configuration
# =============================================
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# =============================================
# SLA Configuration (24 hours in ms)
# =============================================
app.sla.deadline-hours=24

# =============================================
# CORS
# =============================================
app.cors.allowed-origins=http://localhost:5173
